services:
  thea_django:
    build: .
    image: project-thea-api
    command: >
      bash -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      service cron start &&
      python manage.py runserver 0.0.0.0:8000
      "
    container_name: thea_django
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
    depends_on:
      - thea_postgres_db
    networks:
      - thea-network
    stdin_open: true
    tty: true

  thea_postgres_db:
    image: postgres:latest
    container_name: thea_postgres_db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - thea_postgres_db_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - thea-network

  thea_valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: thea_valhalla
    volumes:
      - $HOME/valhalla_custom_files:/custom_files # match this to wherever you keep your custom files
    ports:
      - "8002:8002"
    networks:
      - thea-network

volumes:
  thea_postgres_db_vol:

networks:
  thea-network: