# Generated by Django 5.1 on 2024-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_disease_date_deleted_hotspot_date_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
