# Generated by Django 5.1 on 2024-10-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_disease_created_by_disease_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('subject', 'Subject'), ('admin', 'Admin')], default='subject', max_length=15),
        ),
    ]
