# Generated by Django 5.1 on 2024-11-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('lab_tech', 'Lab_tech'), ('user', 'User'), ('admin', 'Admin')], default='admin', max_length=15),
        ),
    ]
