# Generated by Django 5.1 on 2024-11-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_is_staff_alter_user_is_superuser'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this subject belongs to. A subject will get all permissions granted to each of their groups.', related_name='subject_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='subject',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='subject',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this subject.', related_name='subject_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
