# Generated by Django 5.1 on 2024-11-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_subject_groups_subject_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('lab_tech', 'Lab_tech'), ('user', 'User'), ('admin', 'Admin'), ('subject', 'Subject')], default='admin', max_length=15),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
        ),
    ]
