# Generated by Django 5.1 on 2025-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_user_role_delete_subject_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
