# Generated by Django 5.1 on 2025-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_location_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingMetadata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_processed_timestamp', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
