# Generated by Django 5.1 on 2025-02-19 13:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_processingmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnappedLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapped_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('snapped_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_snapped_location', to=settings.AUTH_USER_MODEL)),
                ('original_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_snapped_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
