name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: docker build -t project-thea-api .

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Start containers
      run: docker compose -f docker-compose-dev.yml up -d

    - name: Wait for PostgreSQL to be ready
      run: |
        until docker exec thea_postgres_db pg_isready -U postgres -h localhost; do
          sleep 1
        done

    - name: Run tests
      run: |
        docker exec thea_postgres_db psql -U postgres -h localhost -c "CREATE DATABASE thea;"
        
        # for debugging
        docker ps -a
        docker logs thea_django # for debugging...
        
        docker exec thea_django python manage.py test