name: Deploy to demo server

on:
    push:
        branches:
            - dev

jobs:
    demo_deploy:
        runs-on: ubuntu-latest
        name: Deploy to demo server
        steps:
            - name: Deploy to demo server
              env:
                SSH_PRIVATE_KEY: ${{ secrets.DEMO_SERVER_SSH_PRIVATE_KEY }}
                SERVER_USER: ${{ secrets.DEMO_SERVER_USER }}
                SERVER_IP: ${{ secrets.DEMO_SERVER_IP }}
              run: |
                mkdir -p ~/.ssh
                chmod 700 ~/.ssh
                eval "$(ssh-agent)"
                echo "$SSH_PRIVATE_KEY" | ssh-add -
                ssh -v -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP /home/nangosha/deploy_demo.sh